import { Email } from "@/types";

export const SEED_EMAILS: Email[] = [
  {
    id: "e1",
    sender: "Sarah Chen",
    email: "sarah.chen@techco.com",
    subject: "Re: Q3 Strategy — can we meet tomorrow?",
    body: "Hi! Would love to catch up on the Q3 roadmap. Are you free tomorrow at 2pm or Thursday afternoon? Also, could you send over the quarterly report before then? It would really help me prep for the board presentation.",
    time: "9:41 AM",
    color: "#7c3aed",
    initials: "SC",
    tags: [],
    classification: null,
    draft: null,
    done: false,
    processing: false,
  },
  {
    id: "e2",
    sender: "James Okonkwo",
    email: "james@vendorpro.com",
    subject: "Invoice #4421 — Payment overdue — URGENT",
    body: "We noticed payment for invoice #4421 ($4,200) is now 14 days overdue. Could you please confirm the status of this payment? We need to resolve this before end of week or we'll have to pause the service contract.",
    time: "9:02 AM",
    color: "#dc2626",
    initials: "JO",
    tags: [],
    classification: null,
    draft: null,
    done: false,
    processing: false,
  },
  {
    id: "e3",
    sender: "CEO · Michael Adeyemi",
    email: "m.adeyemi@company.com",
    subject: "Q3 Report — Need this by Friday EOD",
    body: "Team, please ensure the Q3 performance report is in my inbox by Friday 5pm. This is for the board meeting Monday morning. Please include revenue breakdown, team metrics, and the product roadmap update. High priority — don't miss this deadline.",
    time: "8:15 AM",
    color: "#0284c7",
    initials: "MA",
    tags: [],
    classification: null,
    draft: null,
    done: false,
    processing: false,
  },
  {
    id: "e4",
    sender: "Taiwo Adebisi",
    email: "t.adebisi@partner.ng",
    subject: "Partnership opportunity — SignRig integration?",
    body: "Hi! I came across SignRig and I'm genuinely impressed with the e-signature flow. We run an HR SaaS for 200+ companies in West Africa and would love to explore a white-label integration. Could we schedule a 30-min intro call this week?",
    time: "Yesterday",
    color: "#b45309",
    initials: "TA",
    tags: [],
    classification: null,
    draft: null,
    done: false,
    processing: false,
  },
  {
    id: "e5",
    sender: "ProductHunt Digest",
    email: "digest@producthunt.com",
    subject: "🚀 Today's Top AI Products",
    body: "This week's hottest launches: AI coding assistants, no-code platforms, and developer productivity tools. Plus: the most-upvoted product this week crossed 2,000 upvotes in 24 hours. Check out what's trending.",
    time: "Yesterday",
    color: "#374151",
    initials: "PH",
    tags: [],
    classification: null,
    draft: null,
    done: false,
    processing: false,
  },
];

export const AVATAR_COLORS = [
  "#7c3aed","#dc2626","#0284c7","#059669",
  "#b45309","#0f766e","#9333ea","#c2410c",
];
